### ISSUE TITLE
Разработать функционал добавления операторов

### ISSUE THREAD

**Issue by MrAnuar** [KT-CallCenter/kt-callCenter#6]
**Что нужно сделать**
Разработать функционал добавления операторов.

**Как это сделать**
- Создать контроллеры (get/post) на добавление пользователя
- Создать необходимые сервисы 
- Создать необходимые репозитории
- Создать DTO для используемых моделей
- Создать FTL шаблоны для отображения форм добавления оператора и результат 

**Зачем это нужно**
Для реализации первой версии прототипа необходимы операторы и возможность их добавления через формы.

**Критерии готовности**
- При переходе по ссылке с главного экрана появляется форма добавления оператора.
- Форма имеет простую валидацию.
- Форма корректно добавляет оператора в базу (сущность оператора - Employee)
- После submit на экране отображается результат - оператор добавлен, либо с такими данными уже существует, либо не корректно введены данные.

**Запланированное время:** 10 часов - 05.03.2020. 

**Затраченное время:**3 часа

**Comment by cmontayev** [comment]
Добавил Затраченное время
